{
    "apps": [
        {
            "arch": "arm", 
            "build_date": "2023-12-07_07:56:38", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "d49148b8f19d1ca90001398c3280a783", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.0"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-03-05_17:05:24", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "c058847d5d4eb838a27e100b55c8f04c", 
            "name": "vnt", 
            "tar_url": "vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2022-12-26_08:38:34", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "40fa1121c4946c361c128c8e1acb5c6f", 
            "name": "tailscale", 
            "tar_url": "tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-03-05_08:24:21", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "02031bb8d2a02e52d2fd70800be91193", 
            "name": "socat", 
            "tar_url": "socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.0"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-12-07_07:59:55", 
            "description": "VPN全家桶, ver 4.30 build 9700", 
            "home_url": "Module_softether.asp", 
            "md5": "8caaab38990bf7094210c01c867b4c30", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "2.3"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-01-08_12:43:23", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "321fcd863fa5d93b7b18b827ef8a5f02", 
            "name": "speedtest", 
            "tar_url": "speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.3"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-12-07_08:30:07", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "90469f62264743f7a34803a457488d83", 
            "name": "filebrowser", 
            "tar_url": "filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.6"
        }, 
        {
            "build_date": "2021-12-07_16:27:19", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "879891a46eca0292b1d14ba8fd1f6f18", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-02-18_15:46:56", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "c4cc74927dd874f5ec016025ec6a519d", 
            "name": "aliyundrivewebdav", 
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.1"
        }, 
        {
            "build_date": "2020-08-13_11:56:24", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "306072c6f5e0d991e28baecc678239aa", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2022-07-25_20:08:41", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "829f29cc3a6044b40424fd75a8aefb9b", 
            "name": "phddns", 
            "tar_url": "phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-03-01_12:41:02", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "2df880cd4dfdd37e9c39b656c46aae4e", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-10-24_15:09:14", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "85a04be7687b650af0631a60b3dc9bdd", 
            "name": "unblockmusic", 
            "tar_url": "unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.0"
        }, 
        {
            "build_date": "2021-03-24_20:00:01", 
            "description": "腾讯游戏加速插件", 
            "home_url": "Module_qmacc.asp", 
            "md5": "6cc411d87df5ac46bff0afc1984dad6a", 
            "name": "qmacc", 
            "tar_url": "qmacc/qmacc.tar.gz", 
            "title": "腾讯游戏加速插件", 
            "version": "1.0.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-04-04_13:43:56", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "5d77529bcf7fdd67b819f6f8bed5f72b", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.8"
        }, 
        {
            "build_date": "2021-03-24_19:54:59", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "1852795bf1a14261f1f5a2e71095faa8", 
            "name": "lingti", 
            "tar_url": "lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2022-07-23_13:06:17", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "a678a08fd8e1c2b3f5030f2379a5833c", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "1.9"
        }, 
        {
            "build_date": "2020-08-13_10:29:12", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "43617388b60f9bc09a067a9546f553e2", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-10-24_15:49:13", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "4ed9c3b04756b377a561c965e77d9bbd", 
            "name": "ddns", 
            "tar_url": "ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.2"
        }, 
        {
            "build_date": "2021-04-04_17:10:30", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "c4273479d46e362bf0019d1bce7f4804", 
            "name": "verysync", 
            "tar_url": "verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.0"
        }, 
        {
            "build_date": "2021-03-24_19:44:46", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "23ab187b6f7f9ae6d508745ee2607494", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-02-26_09:55:36", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "88de24013012b240eff378199325ab11", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-04-30_08:23:37", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "8d92b155a3780dccf1df41725eaf6ffd", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-02-19_17:35:36", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "6f74b6ebefe446e7320b061be8e4c6d6", 
            "name": "adbyby", 
            "tar_url": "adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.3"
        }, 
        {
            "build_date": "2020-08-12_14:50:00", 
            "description": "迅雷快鸟，为上网加速而生~", 
            "home_url": "Module_fastd1ck.asp", 
            "md5": "05bba92eb131c48eb73ef30d4b6ad807", 
            "name": "fastd1ck", 
            "tar_url": "fastd1ck/fastd1ck.tar.gz", 
            "title": "讯雷快鸟", 
            "version": "1.8"
        }, 
        {
            "build_date": "2020-08-13_09:57:04", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "13ce6222d901cc86fea7a8c69fa18167", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2022-03-12_20:00:56", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "cafb3299d5bdfdf2833f7c333da411a1", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-02-28_11:58:41", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "b8ee74c8164bdefcbba41ff1476edf0a", 
            "name": "cloudflared", 
            "tar_url": "cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.0"
        }, 
        {
            "build_date": "2020-08-13_09:59:26", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "7765adafa77127178471d0e33743fb96", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.7"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-02-25_22:05:36", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "e6d030db42f6dbc67cb7451e0bebe5ee", 
            "name": "lookcat", 
            "tar_url": "lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-01-08_12:42:39", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "99b03236de41e5ccbed130905480f917", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "2.3"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-02-17_22:56:57", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "272308626853c277ba68646d27b500d9", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-03-19_09:51:18", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "a5040ef4d90e88a3366a4f5a06d1f47e", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "1.9"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-10-24_18:45:32", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "398721143749654b08dacbed66db060d", 
            "name": "alist", 
            "tar_url": "alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-01-08_12:39:14", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "81a2302650894554794686112943c5ec", 
            "name": "baidupcs", 
            "tar_url": "baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.8"
        }, 
        {
            "arch": "arm", 
            "build_date": "2023-04-25_18:32:03", 
            "description": "DDNSTO远程控制", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "6ef294df88300b9fd37b980e144b7fd1", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO远程控制", 
            "version": "3.0.2"
        }, 
        {
            "build_date": "2020-08-13_11:57:17", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "453e2ed739f4d62988266f0fce719670", 
            "name": "tenddns", 
            "tar_url": "tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.2"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/paldier/softcenterarm/master", 
    "md5": "ac396b337b88641f8508504e88c0e1c1", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.5.1"
}